// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: proto/benbroo.proto

package grpcserver

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId   string                 `protobuf:"bytes,1,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	GroupName     string                 `protobuf:"bytes,2,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	ServiceName   string                 `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ClusterName   string                 `protobuf:"bytes,4,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	Ip            string                 `protobuf:"bytes,5,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          int32                  `protobuf:"varint,6,opt,name=port,proto3" json:"port,omitempty"`
	Weight        float64                `protobuf:"fixed64,7,opt,name=weight,proto3" json:"weight,omitempty"`
	Ephemeral     bool                   `protobuf:"varint,8,opt,name=ephemeral,proto3" json:"ephemeral,omitempty"`
	Metadata      string                 `protobuf:"bytes,9,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterInstanceRequest) Reset() {
	*x = RegisterInstanceRequest{}
	mi := &file_proto_benbroo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterInstanceRequest) ProtoMessage() {}

func (x *RegisterInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_benbroo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterInstanceRequest.ProtoReflect.Descriptor instead.
func (*RegisterInstanceRequest) Descriptor() ([]byte, []int) {
	return file_proto_benbroo_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterInstanceRequest) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *RegisterInstanceRequest) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *RegisterInstanceRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *RegisterInstanceRequest) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *RegisterInstanceRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *RegisterInstanceRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *RegisterInstanceRequest) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *RegisterInstanceRequest) GetEphemeral() bool {
	if x != nil {
		return x.Ephemeral
	}
	return false
}

func (x *RegisterInstanceRequest) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

type DeregisterInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId   string                 `protobuf:"bytes,1,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	GroupName     string                 `protobuf:"bytes,2,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	ServiceName   string                 `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ClusterName   string                 `protobuf:"bytes,4,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	Ip            string                 `protobuf:"bytes,5,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          int32                  `protobuf:"varint,6,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterInstanceRequest) Reset() {
	*x = DeregisterInstanceRequest{}
	mi := &file_proto_benbroo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterInstanceRequest) ProtoMessage() {}

func (x *DeregisterInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_benbroo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterInstanceRequest.ProtoReflect.Descriptor instead.
func (*DeregisterInstanceRequest) Descriptor() ([]byte, []int) {
	return file_proto_benbroo_proto_rawDescGZIP(), []int{1}
}

func (x *DeregisterInstanceRequest) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *DeregisterInstanceRequest) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *DeregisterInstanceRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *DeregisterInstanceRequest) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *DeregisterInstanceRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *DeregisterInstanceRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId   string                 `protobuf:"bytes,1,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	GroupName     string                 `protobuf:"bytes,2,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	ServiceName   string                 `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ClusterName   string                 `protobuf:"bytes,4,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	Ip            string                 `protobuf:"bytes,5,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          int32                  `protobuf:"varint,6,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_benbroo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_benbroo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_benbroo_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *HeartbeatRequest) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *HeartbeatRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *HeartbeatRequest) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *HeartbeatRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *HeartbeatRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type InstanceQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId   string                 `protobuf:"bytes,1,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	GroupName     string                 `protobuf:"bytes,2,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	ServiceName   string                 `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	HealthyOnly   bool                   `protobuf:"varint,4,opt,name=healthy_only,json=healthyOnly,proto3" json:"healthy_only,omitempty"`
	Clusters      string                 `protobuf:"bytes,5,opt,name=clusters,proto3" json:"clusters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstanceQuery) Reset() {
	*x = InstanceQuery{}
	mi := &file_proto_benbroo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceQuery) ProtoMessage() {}

func (x *InstanceQuery) ProtoReflect() protoreflect.Message {
	mi := &file_proto_benbroo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceQuery.ProtoReflect.Descriptor instead.
func (*InstanceQuery) Descriptor() ([]byte, []int) {
	return file_proto_benbroo_proto_rawDescGZIP(), []int{3}
}

func (x *InstanceQuery) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *InstanceQuery) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *InstanceQuery) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *InstanceQuery) GetHealthyOnly() bool {
	if x != nil {
		return x.HealthyOnly
	}
	return false
}

func (x *InstanceQuery) GetClusters() string {
	if x != nil {
		return x.Clusters
	}
	return ""
}

type InstanceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	NamespaceId   string                 `protobuf:"bytes,2,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	GroupName     string                 `protobuf:"bytes,3,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	ServiceName   string                 `protobuf:"bytes,4,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ClusterName   string                 `protobuf:"bytes,5,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	Ip            string                 `protobuf:"bytes,6,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          int32                  `protobuf:"varint,7,opt,name=port,proto3" json:"port,omitempty"`
	Weight        float64                `protobuf:"fixed64,8,opt,name=weight,proto3" json:"weight,omitempty"`
	Healthy       bool                   `protobuf:"varint,9,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Enabled       bool                   `protobuf:"varint,10,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Ephemeral     bool                   `protobuf:"varint,11,opt,name=ephemeral,proto3" json:"ephemeral,omitempty"`
	Metadata      string                 `protobuf:"bytes,12,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstanceInfo) Reset() {
	*x = InstanceInfo{}
	mi := &file_proto_benbroo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceInfo) ProtoMessage() {}

func (x *InstanceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_benbroo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceInfo.ProtoReflect.Descriptor instead.
func (*InstanceInfo) Descriptor() ([]byte, []int) {
	return file_proto_benbroo_proto_rawDescGZIP(), []int{4}
}

func (x *InstanceInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *InstanceInfo) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *InstanceInfo) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *InstanceInfo) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *InstanceInfo) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *InstanceInfo) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *InstanceInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *InstanceInfo) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *InstanceInfo) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *InstanceInfo) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *InstanceInfo) GetEphemeral() bool {
	if x != nil {
		return x.Ephemeral
	}
	return false
}

func (x *InstanceInfo) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

type InstanceListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instances     []*InstanceInfo        `protobuf:"bytes,1,rep,name=instances,proto3" json:"instances,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstanceListResponse) Reset() {
	*x = InstanceListResponse{}
	mi := &file_proto_benbroo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceListResponse) ProtoMessage() {}

func (x *InstanceListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_benbroo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceListResponse.ProtoReflect.Descriptor instead.
func (*InstanceListResponse) Descriptor() ([]byte, []int) {
	return file_proto_benbroo_proto_rawDescGZIP(), []int{5}
}

func (x *InstanceListResponse) GetInstances() []*InstanceInfo {
	if x != nil {
		return x.Instances
	}
	return nil
}

func (x *InstanceListResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ConfigQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId   string                 `protobuf:"bytes,1,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	GroupName     string                 `protobuf:"bytes,2,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	DataId        string                 `protobuf:"bytes,3,opt,name=data_id,json=dataId,proto3" json:"data_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigQuery) Reset() {
	*x = ConfigQuery{}
	mi := &file_proto_benbroo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigQuery) ProtoMessage() {}

func (x *ConfigQuery) ProtoReflect() protoreflect.Message {
	mi := &file_proto_benbroo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigQuery.ProtoReflect.Descriptor instead.
func (*ConfigQuery) Descriptor() ([]byte, []int) {
	return file_proto_benbroo_proto_rawDescGZIP(), []int{6}
}

func (x *ConfigQuery) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *ConfigQuery) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *ConfigQuery) GetDataId() string {
	if x != nil {
		return x.DataId
	}
	return ""
}

type ConfigPublishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId   string                 `protobuf:"bytes,1,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	GroupName     string                 `protobuf:"bytes,2,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	DataId        string                 `protobuf:"bytes,3,opt,name=data_id,json=dataId,proto3" json:"data_id,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigPublishRequest) Reset() {
	*x = ConfigPublishRequest{}
	mi := &file_proto_benbroo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigPublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigPublishRequest) ProtoMessage() {}

func (x *ConfigPublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_benbroo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigPublishRequest.ProtoReflect.Descriptor instead.
func (*ConfigPublishRequest) Descriptor() ([]byte, []int) {
	return file_proto_benbroo_proto_rawDescGZIP(), []int{7}
}

func (x *ConfigPublishRequest) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *ConfigPublishRequest) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *ConfigPublishRequest) GetDataId() string {
	if x != nil {
		return x.DataId
	}
	return ""
}

func (x *ConfigPublishRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ConfigPublishRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type ConfigInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId   string                 `protobuf:"bytes,1,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	GroupName     string                 `protobuf:"bytes,2,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	DataId        string                 `protobuf:"bytes,3,opt,name=data_id,json=dataId,proto3" json:"data_id,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Md5           string                 `protobuf:"bytes,5,opt,name=md5,proto3" json:"md5,omitempty"`
	Type          string                 `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigInfo) Reset() {
	*x = ConfigInfo{}
	mi := &file_proto_benbroo_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigInfo) ProtoMessage() {}

func (x *ConfigInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_benbroo_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigInfo.ProtoReflect.Descriptor instead.
func (*ConfigInfo) Descriptor() ([]byte, []int) {
	return file_proto_benbroo_proto_rawDescGZIP(), []int{8}
}

func (x *ConfigInfo) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *ConfigInfo) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *ConfigInfo) GetDataId() string {
	if x != nil {
		return x.DataId
	}
	return ""
}

func (x *ConfigInfo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ConfigInfo) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

func (x *ConfigInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type ConfigListenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId   string                 `protobuf:"bytes,1,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	GroupName     string                 `protobuf:"bytes,2,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	DataId        string                 `protobuf:"bytes,3,opt,name=data_id,json=dataId,proto3" json:"data_id,omitempty"`
	Md5           string                 `protobuf:"bytes,4,opt,name=md5,proto3" json:"md5,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigListenRequest) Reset() {
	*x = ConfigListenRequest{}
	mi := &file_proto_benbroo_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigListenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigListenRequest) ProtoMessage() {}

func (x *ConfigListenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_benbroo_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigListenRequest.ProtoReflect.Descriptor instead.
func (*ConfigListenRequest) Descriptor() ([]byte, []int) {
	return file_proto_benbroo_proto_rawDescGZIP(), []int{9}
}

func (x *ConfigListenRequest) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *ConfigListenRequest) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *ConfigListenRequest) GetDataId() string {
	if x != nil {
		return x.DataId
	}
	return ""
}

func (x *ConfigListenRequest) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

type ConfigChangedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Changed       bool                   `protobuf:"varint,1,opt,name=changed,proto3" json:"changed,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Md5           string                 `protobuf:"bytes,3,opt,name=md5,proto3" json:"md5,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigChangedResponse) Reset() {
	*x = ConfigChangedResponse{}
	mi := &file_proto_benbroo_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigChangedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigChangedResponse) ProtoMessage() {}

func (x *ConfigChangedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_benbroo_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigChangedResponse.ProtoReflect.Descriptor instead.
func (*ConfigChangedResponse) Descriptor() ([]byte, []int) {
	return file_proto_benbroo_proto_rawDescGZIP(), []int{10}
}

func (x *ConfigChangedResponse) GetChanged() bool {
	if x != nil {
		return x.Changed
	}
	return false
}

func (x *ConfigChangedResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ConfigChangedResponse) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

type HealthReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId   string                 `protobuf:"bytes,1,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	GroupName     string                 `protobuf:"bytes,2,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	ServiceName   string                 `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Ip            string                 `protobuf:"bytes,4,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          int32                  `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthReportRequest) Reset() {
	*x = HealthReportRequest{}
	mi := &file_proto_benbroo_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthReportRequest) ProtoMessage() {}

func (x *HealthReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_benbroo_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthReportRequest.ProtoReflect.Descriptor instead.
func (*HealthReportRequest) Descriptor() ([]byte, []int) {
	return file_proto_benbroo_proto_rawDescGZIP(), []int{11}
}

func (x *HealthReportRequest) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *HealthReportRequest) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *HealthReportRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *HealthReportRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *HealthReportRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_proto_benbroo_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_benbroo_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_benbroo_proto_rawDescGZIP(), []int{12}
}

func (x *Response) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_benbroo_proto protoreflect.FileDescriptor

const file_proto_benbroo_proto_rawDesc = "" +
	"\n" +
	"\x13proto/benbroo.proto\x12\abenbroo\"\x97\x02\n" +
	"\x17RegisterInstanceRequest\x12!\n" +
	"\fnamespace_id\x18\x01 \x01(\tR\vnamespaceId\x12\x1d\n" +
	"\n" +
	"group_name\x18\x02 \x01(\tR\tgroupName\x12!\n" +
	"\fservice_name\x18\x03 \x01(\tR\vserviceName\x12!\n" +
	"\fcluster_name\x18\x04 \x01(\tR\vclusterName\x12\x0e\n" +
	"\x02ip\x18\x05 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x06 \x01(\x05R\x04port\x12\x16\n" +
	"\x06weight\x18\a \x01(\x01R\x06weight\x12\x1c\n" +
	"\tephemeral\x18\b \x01(\bR\tephemeral\x12\x1a\n" +
	"\bmetadata\x18\t \x01(\tR\bmetadata\"\xc7\x01\n" +
	"\x19DeregisterInstanceRequest\x12!\n" +
	"\fnamespace_id\x18\x01 \x01(\tR\vnamespaceId\x12\x1d\n" +
	"\n" +
	"group_name\x18\x02 \x01(\tR\tgroupName\x12!\n" +
	"\fservice_name\x18\x03 \x01(\tR\vserviceName\x12!\n" +
	"\fcluster_name\x18\x04 \x01(\tR\vclusterName\x12\x0e\n" +
	"\x02ip\x18\x05 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x06 \x01(\x05R\x04port\"\xbe\x01\n" +
	"\x10HeartbeatRequest\x12!\n" +
	"\fnamespace_id\x18\x01 \x01(\tR\vnamespaceId\x12\x1d\n" +
	"\n" +
	"group_name\x18\x02 \x01(\tR\tgroupName\x12!\n" +
	"\fservice_name\x18\x03 \x01(\tR\vserviceName\x12!\n" +
	"\fcluster_name\x18\x04 \x01(\tR\vclusterName\x12\x0e\n" +
	"\x02ip\x18\x05 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x06 \x01(\x05R\x04port\"\xb3\x01\n" +
	"\rInstanceQuery\x12!\n" +
	"\fnamespace_id\x18\x01 \x01(\tR\vnamespaceId\x12\x1d\n" +
	"\n" +
	"group_name\x18\x02 \x01(\tR\tgroupName\x12!\n" +
	"\fservice_name\x18\x03 \x01(\tR\vserviceName\x12!\n" +
	"\fhealthy_only\x18\x04 \x01(\bR\vhealthyOnly\x12\x1a\n" +
	"\bclusters\x18\x05 \x01(\tR\bclusters\"\xd0\x02\n" +
	"\fInstanceInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12!\n" +
	"\fnamespace_id\x18\x02 \x01(\tR\vnamespaceId\x12\x1d\n" +
	"\n" +
	"group_name\x18\x03 \x01(\tR\tgroupName\x12!\n" +
	"\fservice_name\x18\x04 \x01(\tR\vserviceName\x12!\n" +
	"\fcluster_name\x18\x05 \x01(\tR\vclusterName\x12\x0e\n" +
	"\x02ip\x18\x06 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\a \x01(\x05R\x04port\x12\x16\n" +
	"\x06weight\x18\b \x01(\x01R\x06weight\x12\x18\n" +
	"\ahealthy\x18\t \x01(\bR\ahealthy\x12\x18\n" +
	"\aenabled\x18\n" +
	" \x01(\bR\aenabled\x12\x1c\n" +
	"\tephemeral\x18\v \x01(\bR\tephemeral\x12\x1a\n" +
	"\bmetadata\x18\f \x01(\tR\bmetadata\"a\n" +
	"\x14InstanceListResponse\x123\n" +
	"\tinstances\x18\x01 \x03(\v2\x15.benbroo.InstanceInfoR\tinstances\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"h\n" +
	"\vConfigQuery\x12!\n" +
	"\fnamespace_id\x18\x01 \x01(\tR\vnamespaceId\x12\x1d\n" +
	"\n" +
	"group_name\x18\x02 \x01(\tR\tgroupName\x12\x17\n" +
	"\adata_id\x18\x03 \x01(\tR\x06dataId\"\x9f\x01\n" +
	"\x14ConfigPublishRequest\x12!\n" +
	"\fnamespace_id\x18\x01 \x01(\tR\vnamespaceId\x12\x1d\n" +
	"\n" +
	"group_name\x18\x02 \x01(\tR\tgroupName\x12\x17\n" +
	"\adata_id\x18\x03 \x01(\tR\x06dataId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\"\xa7\x01\n" +
	"\n" +
	"ConfigInfo\x12!\n" +
	"\fnamespace_id\x18\x01 \x01(\tR\vnamespaceId\x12\x1d\n" +
	"\n" +
	"group_name\x18\x02 \x01(\tR\tgroupName\x12\x17\n" +
	"\adata_id\x18\x03 \x01(\tR\x06dataId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x10\n" +
	"\x03md5\x18\x05 \x01(\tR\x03md5\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\"\x82\x01\n" +
	"\x13ConfigListenRequest\x12!\n" +
	"\fnamespace_id\x18\x01 \x01(\tR\vnamespaceId\x12\x1d\n" +
	"\n" +
	"group_name\x18\x02 \x01(\tR\tgroupName\x12\x17\n" +
	"\adata_id\x18\x03 \x01(\tR\x06dataId\x12\x10\n" +
	"\x03md5\x18\x04 \x01(\tR\x03md5\"]\n" +
	"\x15ConfigChangedResponse\x12\x18\n" +
	"\achanged\x18\x01 \x01(\bR\achanged\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x10\n" +
	"\x03md5\x18\x03 \x01(\tR\x03md5\"\x9e\x01\n" +
	"\x13HealthReportRequest\x12!\n" +
	"\fnamespace_id\x18\x01 \x01(\tR\vnamespaceId\x12\x1d\n" +
	"\n" +
	"group_name\x18\x02 \x01(\tR\tgroupName\x12!\n" +
	"\fservice_name\x18\x03 \x01(\tR\vserviceName\x12\x0e\n" +
	"\x02ip\x18\x04 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x05 \x01(\x05R\x04port\"8\n" +
	"\bResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xa7\x02\n" +
	"\rNamingService\x12G\n" +
	"\x10RegisterInstance\x12 .benbroo.RegisterInstanceRequest\x1a\x11.benbroo.Response\x12K\n" +
	"\x12DeregisterInstance\x12\".benbroo.DeregisterInstanceRequest\x1a\x11.benbroo.Response\x129\n" +
	"\tHeartbeat\x12\x19.benbroo.HeartbeatRequest\x1a\x11.benbroo.Response\x12E\n" +
	"\fGetInstances\x12\x16.benbroo.InstanceQuery\x1a\x1d.benbroo.InstanceListResponse2\xd8\x01\n" +
	"\rConfigService\x126\n" +
	"\tGetConfig\x12\x14.benbroo.ConfigQuery\x1a\x13.benbroo.ConfigInfo\x12A\n" +
	"\rPublishConfig\x12\x1d.benbroo.ConfigPublishRequest\x1a\x11.benbroo.Response\x12L\n" +
	"\fListenConfig\x12\x1c.benbroo.ConfigListenRequest\x1a\x1e.benbroo.ConfigChangedResponse2\x93\x01\n" +
	"\rHealthService\x12@\n" +
	"\rReportFailure\x12\x1c.benbroo.HealthReportRequest\x1a\x11.benbroo.Response\x12@\n" +
	"\rReportSuccess\x12\x1c.benbroo.HealthReportRequest\x1a\x11.benbroo.ResponseB+Z)github.com/benbroo/benbroo/pkg/grpcserverb\x06proto3"

var (
	file_proto_benbroo_proto_rawDescOnce sync.Once
	file_proto_benbroo_proto_rawDescData []byte
)

func file_proto_benbroo_proto_rawDescGZIP() []byte {
	file_proto_benbroo_proto_rawDescOnce.Do(func() {
		file_proto_benbroo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_benbroo_proto_rawDesc), len(file_proto_benbroo_proto_rawDesc)))
	})
	return file_proto_benbroo_proto_rawDescData
}

var file_proto_benbroo_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_benbroo_proto_goTypes = []any{
	(*RegisterInstanceRequest)(nil),   // 0: benbroo.RegisterInstanceRequest
	(*DeregisterInstanceRequest)(nil), // 1: benbroo.DeregisterInstanceRequest
	(*HeartbeatRequest)(nil),          // 2: benbroo.HeartbeatRequest
	(*InstanceQuery)(nil),             // 3: benbroo.InstanceQuery
	(*InstanceInfo)(nil),              // 4: benbroo.InstanceInfo
	(*InstanceListResponse)(nil),      // 5: benbroo.InstanceListResponse
	(*ConfigQuery)(nil),               // 6: benbroo.ConfigQuery
	(*ConfigPublishRequest)(nil),      // 7: benbroo.ConfigPublishRequest
	(*ConfigInfo)(nil),                // 8: benbroo.ConfigInfo
	(*ConfigListenRequest)(nil),       // 9: benbroo.ConfigListenRequest
	(*ConfigChangedResponse)(nil),     // 10: benbroo.ConfigChangedResponse
	(*HealthReportRequest)(nil),       // 11: benbroo.HealthReportRequest
	(*Response)(nil),                  // 12: benbroo.Response
}
var file_proto_benbroo_proto_depIdxs = []int32{
	4,  // 0: benbroo.InstanceListResponse.instances:type_name -> benbroo.InstanceInfo
	0,  // 1: benbroo.NamingService.RegisterInstance:input_type -> benbroo.RegisterInstanceRequest
	1,  // 2: benbroo.NamingService.DeregisterInstance:input_type -> benbroo.DeregisterInstanceRequest
	2,  // 3: benbroo.NamingService.Heartbeat:input_type -> benbroo.HeartbeatRequest
	3,  // 4: benbroo.NamingService.GetInstances:input_type -> benbroo.InstanceQuery
	6,  // 5: benbroo.ConfigService.GetConfig:input_type -> benbroo.ConfigQuery
	7,  // 6: benbroo.ConfigService.PublishConfig:input_type -> benbroo.ConfigPublishRequest
	9,  // 7: benbroo.ConfigService.ListenConfig:input_type -> benbroo.ConfigListenRequest
	11, // 8: benbroo.HealthService.ReportFailure:input_type -> benbroo.HealthReportRequest
	11, // 9: benbroo.HealthService.ReportSuccess:input_type -> benbroo.HealthReportRequest
	12, // 10: benbroo.NamingService.RegisterInstance:output_type -> benbroo.Response
	12, // 11: benbroo.NamingService.DeregisterInstance:output_type -> benbroo.Response
	12, // 12: benbroo.NamingService.Heartbeat:output_type -> benbroo.Response
	5,  // 13: benbroo.NamingService.GetInstances:output_type -> benbroo.InstanceListResponse
	8,  // 14: benbroo.ConfigService.GetConfig:output_type -> benbroo.ConfigInfo
	12, // 15: benbroo.ConfigService.PublishConfig:output_type -> benbroo.Response
	10, // 16: benbroo.ConfigService.ListenConfig:output_type -> benbroo.ConfigChangedResponse
	12, // 17: benbroo.HealthService.ReportFailure:output_type -> benbroo.Response
	12, // 18: benbroo.HealthService.ReportSuccess:output_type -> benbroo.Response
	10, // [10:19] is the sub-list for method output_type
	1,  // [1:10] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_proto_benbroo_proto_init() }
func file_proto_benbroo_proto_init() {
	if File_proto_benbroo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_benbroo_proto_rawDesc), len(file_proto_benbroo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_proto_benbroo_proto_goTypes,
		DependencyIndexes: file_proto_benbroo_proto_depIdxs,
		MessageInfos:      file_proto_benbroo_proto_msgTypes,
	}.Build()
	File_proto_benbroo_proto = out.File
	file_proto_benbroo_proto_goTypes = nil
	file_proto_benbroo_proto_depIdxs = nil
}
