// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.28.3
// source: proto/benbroo.proto

package grpcserver

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NamingService_RegisterInstance_FullMethodName   = "/benbroo.NamingService/RegisterInstance"
	NamingService_DeregisterInstance_FullMethodName = "/benbroo.NamingService/DeregisterInstance"
	NamingService_Heartbeat_FullMethodName          = "/benbroo.NamingService/Heartbeat"
	NamingService_GetInstances_FullMethodName       = "/benbroo.NamingService/GetInstances"
)

// NamingServiceClient is the client API for NamingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NamingServiceClient interface {
	RegisterInstance(ctx context.Context, in *RegisterInstanceRequest, opts ...grpc.CallOption) (*Response, error)
	DeregisterInstance(ctx context.Context, in *DeregisterInstanceRequest, opts ...grpc.CallOption) (*Response, error)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*Response, error)
	GetInstances(ctx context.Context, in *InstanceQuery, opts ...grpc.CallOption) (*InstanceListResponse, error)
}

type namingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNamingServiceClient(cc grpc.ClientConnInterface) NamingServiceClient {
	return &namingServiceClient{cc}
}

func (c *namingServiceClient) RegisterInstance(ctx context.Context, in *RegisterInstanceRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, NamingService_RegisterInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *namingServiceClient) DeregisterInstance(ctx context.Context, in *DeregisterInstanceRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, NamingService_DeregisterInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *namingServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, NamingService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *namingServiceClient) GetInstances(ctx context.Context, in *InstanceQuery, opts ...grpc.CallOption) (*InstanceListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstanceListResponse)
	err := c.cc.Invoke(ctx, NamingService_GetInstances_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NamingServiceServer is the server API for NamingService service.
// All implementations must embed UnimplementedNamingServiceServer
// for forward compatibility.
type NamingServiceServer interface {
	RegisterInstance(context.Context, *RegisterInstanceRequest) (*Response, error)
	DeregisterInstance(context.Context, *DeregisterInstanceRequest) (*Response, error)
	Heartbeat(context.Context, *HeartbeatRequest) (*Response, error)
	GetInstances(context.Context, *InstanceQuery) (*InstanceListResponse, error)
	mustEmbedUnimplementedNamingServiceServer()
}

// UnimplementedNamingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNamingServiceServer struct{}

func (UnimplementedNamingServiceServer) RegisterInstance(context.Context, *RegisterInstanceRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterInstance not implemented")
}
func (UnimplementedNamingServiceServer) DeregisterInstance(context.Context, *DeregisterInstanceRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method DeregisterInstance not implemented")
}
func (UnimplementedNamingServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedNamingServiceServer) GetInstances(context.Context, *InstanceQuery) (*InstanceListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInstances not implemented")
}
func (UnimplementedNamingServiceServer) mustEmbedUnimplementedNamingServiceServer() {}
func (UnimplementedNamingServiceServer) testEmbeddedByValue()                       {}

// UnsafeNamingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NamingServiceServer will
// result in compilation errors.
type UnsafeNamingServiceServer interface {
	mustEmbedUnimplementedNamingServiceServer()
}

func RegisterNamingServiceServer(s grpc.ServiceRegistrar, srv NamingServiceServer) {
	// If the following call panics, it indicates UnimplementedNamingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NamingService_ServiceDesc, srv)
}

func _NamingService_RegisterInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NamingServiceServer).RegisterInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NamingService_RegisterInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NamingServiceServer).RegisterInstance(ctx, req.(*RegisterInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NamingService_DeregisterInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeregisterInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NamingServiceServer).DeregisterInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NamingService_DeregisterInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NamingServiceServer).DeregisterInstance(ctx, req.(*DeregisterInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NamingService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NamingServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NamingService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NamingServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NamingService_GetInstances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstanceQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NamingServiceServer).GetInstances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NamingService_GetInstances_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NamingServiceServer).GetInstances(ctx, req.(*InstanceQuery))
	}
	return interceptor(ctx, in, info, handler)
}

// NamingService_ServiceDesc is the grpc.ServiceDesc for NamingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NamingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "benbroo.NamingService",
	HandlerType: (*NamingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterInstance",
			Handler:    _NamingService_RegisterInstance_Handler,
		},
		{
			MethodName: "DeregisterInstance",
			Handler:    _NamingService_DeregisterInstance_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _NamingService_Heartbeat_Handler,
		},
		{
			MethodName: "GetInstances",
			Handler:    _NamingService_GetInstances_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/benbroo.proto",
}

const (
	ConfigService_GetConfig_FullMethodName     = "/benbroo.ConfigService/GetConfig"
	ConfigService_PublishConfig_FullMethodName = "/benbroo.ConfigService/PublishConfig"
	ConfigService_ListenConfig_FullMethodName  = "/benbroo.ConfigService/ListenConfig"
)

// ConfigServiceClient is the client API for ConfigService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConfigServiceClient interface {
	GetConfig(ctx context.Context, in *ConfigQuery, opts ...grpc.CallOption) (*ConfigInfo, error)
	PublishConfig(ctx context.Context, in *ConfigPublishRequest, opts ...grpc.CallOption) (*Response, error)
	ListenConfig(ctx context.Context, in *ConfigListenRequest, opts ...grpc.CallOption) (*ConfigChangedResponse, error)
}

type configServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConfigServiceClient(cc grpc.ClientConnInterface) ConfigServiceClient {
	return &configServiceClient{cc}
}

func (c *configServiceClient) GetConfig(ctx context.Context, in *ConfigQuery, opts ...grpc.CallOption) (*ConfigInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigInfo)
	err := c.cc.Invoke(ctx, ConfigService_GetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) PublishConfig(ctx context.Context, in *ConfigPublishRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, ConfigService_PublishConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) ListenConfig(ctx context.Context, in *ConfigListenRequest, opts ...grpc.CallOption) (*ConfigChangedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigChangedResponse)
	err := c.cc.Invoke(ctx, ConfigService_ListenConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConfigServiceServer is the server API for ConfigService service.
// All implementations must embed UnimplementedConfigServiceServer
// for forward compatibility.
type ConfigServiceServer interface {
	GetConfig(context.Context, *ConfigQuery) (*ConfigInfo, error)
	PublishConfig(context.Context, *ConfigPublishRequest) (*Response, error)
	ListenConfig(context.Context, *ConfigListenRequest) (*ConfigChangedResponse, error)
	mustEmbedUnimplementedConfigServiceServer()
}

// UnimplementedConfigServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConfigServiceServer struct{}

func (UnimplementedConfigServiceServer) GetConfig(context.Context, *ConfigQuery) (*ConfigInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConfig not implemented")
}
func (UnimplementedConfigServiceServer) PublishConfig(context.Context, *ConfigPublishRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishConfig not implemented")
}
func (UnimplementedConfigServiceServer) ListenConfig(context.Context, *ConfigListenRequest) (*ConfigChangedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListenConfig not implemented")
}
func (UnimplementedConfigServiceServer) mustEmbedUnimplementedConfigServiceServer() {}
func (UnimplementedConfigServiceServer) testEmbeddedByValue()                       {}

// UnsafeConfigServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfigServiceServer will
// result in compilation errors.
type UnsafeConfigServiceServer interface {
	mustEmbedUnimplementedConfigServiceServer()
}

func RegisterConfigServiceServer(s grpc.ServiceRegistrar, srv ConfigServiceServer) {
	// If the following call panics, it indicates UnimplementedConfigServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConfigService_ServiceDesc, srv)
}

func _ConfigService_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigService_GetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).GetConfig(ctx, req.(*ConfigQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_PublishConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigPublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).PublishConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigService_PublishConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).PublishConfig(ctx, req.(*ConfigPublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_ListenConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigListenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).ListenConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigService_ListenConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).ListenConfig(ctx, req.(*ConfigListenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConfigService_ServiceDesc is the grpc.ServiceDesc for ConfigService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConfigService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "benbroo.ConfigService",
	HandlerType: (*ConfigServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConfig",
			Handler:    _ConfigService_GetConfig_Handler,
		},
		{
			MethodName: "PublishConfig",
			Handler:    _ConfigService_PublishConfig_Handler,
		},
		{
			MethodName: "ListenConfig",
			Handler:    _ConfigService_ListenConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/benbroo.proto",
}

const (
	HealthService_ReportFailure_FullMethodName = "/benbroo.HealthService/ReportFailure"
	HealthService_ReportSuccess_FullMethodName = "/benbroo.HealthService/ReportSuccess"
)

// HealthServiceClient is the client API for HealthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HealthServiceClient interface {
	ReportFailure(ctx context.Context, in *HealthReportRequest, opts ...grpc.CallOption) (*Response, error)
	ReportSuccess(ctx context.Context, in *HealthReportRequest, opts ...grpc.CallOption) (*Response, error)
}

type healthServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHealthServiceClient(cc grpc.ClientConnInterface) HealthServiceClient {
	return &healthServiceClient{cc}
}

func (c *healthServiceClient) ReportFailure(ctx context.Context, in *HealthReportRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, HealthService_ReportFailure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *healthServiceClient) ReportSuccess(ctx context.Context, in *HealthReportRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, HealthService_ReportSuccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HealthServiceServer is the server API for HealthService service.
// All implementations must embed UnimplementedHealthServiceServer
// for forward compatibility.
type HealthServiceServer interface {
	ReportFailure(context.Context, *HealthReportRequest) (*Response, error)
	ReportSuccess(context.Context, *HealthReportRequest) (*Response, error)
	mustEmbedUnimplementedHealthServiceServer()
}

// UnimplementedHealthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHealthServiceServer struct{}

func (UnimplementedHealthServiceServer) ReportFailure(context.Context, *HealthReportRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportFailure not implemented")
}
func (UnimplementedHealthServiceServer) ReportSuccess(context.Context, *HealthReportRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportSuccess not implemented")
}
func (UnimplementedHealthServiceServer) mustEmbedUnimplementedHealthServiceServer() {}
func (UnimplementedHealthServiceServer) testEmbeddedByValue()                       {}

// UnsafeHealthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HealthServiceServer will
// result in compilation errors.
type UnsafeHealthServiceServer interface {
	mustEmbedUnimplementedHealthServiceServer()
}

func RegisterHealthServiceServer(s grpc.ServiceRegistrar, srv HealthServiceServer) {
	// If the following call panics, it indicates UnimplementedHealthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HealthService_ServiceDesc, srv)
}

func _HealthService_ReportFailure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServiceServer).ReportFailure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HealthService_ReportFailure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServiceServer).ReportFailure(ctx, req.(*HealthReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HealthService_ReportSuccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServiceServer).ReportSuccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HealthService_ReportSuccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServiceServer).ReportSuccess(ctx, req.(*HealthReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HealthService_ServiceDesc is the grpc.ServiceDesc for HealthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HealthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "benbroo.HealthService",
	HandlerType: (*HealthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportFailure",
			Handler:    _HealthService_ReportFailure_Handler,
		},
		{
			MethodName: "ReportSuccess",
			Handler:    _HealthService_ReportSuccess_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/benbroo.proto",
}
